// Copyright 2026 Ego Hygiene
// SPDX-License-Identifier: MIT

//! Visual-motion policy, provenance, and quality-harness extension.
//!
//! Motion remains a derived presentation concern. The module validates
//! versioned metadata and generated bytes, then contributes checks to the
//! existing `identity.quality-report/v1` decision. It does not publish assets,
//! capture browsers, or approve creative intent.

#[cfg(test)]
mod tests;

use std::collections::BTreeSet;

use serde::{Deserialize, Serialize};

use crate::compiler::{CompilerError, CompilerResult, Diagnostic, FailureKind, sha256_hex};
use crate::quality::{
    HumanReviewEvidence, QualityCategory, QualityCheck, QualityCoverage, QualityHarness,
    QualityInput, QualityReport, QualityStatus,
};

pub const MOTION_POLICY_SCHEMA: &str = "identity.motion-policy/v1";
pub const VISUAL_MOTION_MANIFEST_SCHEMA: &str = "identity.visual-motion-manifest/v1";

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct MotionDurationBudgets {
    pub micro_interaction: u64,
    pub transition: u64,
    pub landing_sequence: u64,
    pub continuous_status: u64,
    pub demo_capture: u64,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct MotionAssetBudgets {
    pub micro_interaction: u64,
    pub transition: u64,
    pub landing_sequence: u64,
    pub continuous_status: u64,
    pub demo_capture: u64,
    pub static_imagery: u64,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct MotionPolicy {
    pub schema: String,
    pub durations_ms: MotionDurationBudgets,
    pub asset_bytes: MotionAssetBudgets,
    pub maximum_frame_rate: f64,
    pub maximum_dimension_pixels: u32,
    pub allowed_animated_properties: BTreeSet<String>,
    pub allowed_easing: BTreeSet<String>,
    pub allowed_network_modes: BTreeSet<MotionNetworkMode>,
}

impl Default for MotionPolicy {
    fn default() -> Self {
        Self {
            schema: MOTION_POLICY_SCHEMA.to_owned(),
            durations_ms: MotionDurationBudgets {
                micro_interaction: 200,
                transition: 500,
                landing_sequence: 2_000,
                continuous_status: 2_000,
                demo_capture: 15_000,
            },
            asset_bytes: MotionAssetBudgets {
                micro_interaction: 256 * 1024,
                transition: 512 * 1024,
                landing_sequence: 1024 * 1024,
                continuous_status: 512 * 1024,
                demo_capture: 4 * 1024 * 1024,
                static_imagery: 1024 * 1024,
            },
            maximum_frame_rate: 60.0,
            maximum_dimension_pixels: 3_840,
            allowed_animated_properties: BTreeSet::from([
                "opacity".to_owned(),
                "transform".to_owned(),
            ]),
            allowed_easing: BTreeSet::from([
                "ease-out".to_owned(),
                "ease-out-expo".to_owned(),
                "ease-out-quart".to_owned(),
                "ease-out-quint".to_owned(),
                "standard".to_owned(),
            ]),
            allowed_network_modes: BTreeSet::from([
                MotionNetworkMode::Offline,
                MotionNetworkMode::RecordedFixture,
            ]),
        }
    }
}

impl MotionPolicy {
    fn validate(&self) -> CompilerResult<()> {
        if self.schema != MOTION_POLICY_SCHEMA {
            return Err(motion_error(
                "motion-policy",
                format!("unsupported motion policy schema {:?}", self.schema),
                "Use identity.motion-policy/v1 before running motion quality checks.",
            ));
        }
        if !self.maximum_frame_rate.is_finite() || self.maximum_frame_rate <= 0.0 {
            return Err(motion_error(
                "maximumFrameRate",
                "motion policy frame-rate budget must be a positive finite number".to_owned(),
                "Set a positive finite maximum frame rate.",
            ));
        }
        if self.maximum_dimension_pixels == 0 {
            return Err(motion_error(
                "maximumDimensionPixels",
                "motion policy dimension budget must be greater than zero".to_owned(),
                "Set a positive maximum output dimension.",
            ));
        }
        if self.allowed_animated_properties.is_empty()
            || self.allowed_easing.is_empty()
            || self.allowed_network_modes.is_empty()
        {
            return Err(motion_error(
                "motion-policy",
                "motion policy allow-lists must not be empty".to_owned(),
                "Declare at least one allowed property, easing, and deterministic network mode.",
            ));
        }
        Ok(())
    }

    fn duration_budget(&self, purpose: MotionPurpose) -> Option<u64> {
        match purpose {
            MotionPurpose::MicroInteraction => Some(self.durations_ms.micro_interaction),
            MotionPurpose::Transition => Some(self.durations_ms.transition),
            MotionPurpose::LandingSequence => Some(self.durations_ms.landing_sequence),
            MotionPurpose::ContinuousStatus => Some(self.durations_ms.continuous_status),
            MotionPurpose::DemoCapture => Some(self.durations_ms.demo_capture),
            MotionPurpose::StaticImagery => None,
        }
    }

    fn byte_budget(&self, purpose: MotionPurpose) -> u64 {
        match purpose {
            MotionPurpose::MicroInteraction => self.asset_bytes.micro_interaction,
            MotionPurpose::Transition => self.asset_bytes.transition,
            MotionPurpose::LandingSequence => self.asset_bytes.landing_sequence,
            MotionPurpose::ContinuousStatus => self.asset_bytes.continuous_status,
            MotionPurpose::DemoCapture => self.asset_bytes.demo_capture,
            MotionPurpose::StaticImagery => self.asset_bytes.static_imagery,
        }
    }
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum VisualMotionKind {
    Animation,
    Imagery,
    DemoCapture,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum MotionPurpose {
    MicroInteraction,
    Transition,
    LandingSequence,
    ContinuousStatus,
    DemoCapture,
    StaticImagery,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum ReducedMotionBehavior {
    Instant,
    StaticFallback,
    PairedReducedCapture,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum MotionNetworkMode {
    Offline,
    RecordedFixture,
    Live,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum VisualMotionSourceMethod {
    FirstParty,
    Captured,
    Generated,
    Licensed,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct VisualMotionSource {
    pub creator: String,
    pub method: VisualMotionSourceMethod,
    pub reference: String,
    pub sha256: String,
    pub license_spdx: String,
    pub approval: String,
    #[serde(default)]
    pub repository: Option<String>,
    #[serde(default)]
    pub commit: Option<String>,
    #[serde(default)]
    pub script_path: Option<String>,
    #[serde(default)]
    pub fixture_path: Option<String>,
    #[serde(default)]
    pub fixture_sha256: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct VisualMotionGenerator {
    pub id: String,
    pub version: String,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct VisualMotionOutput {
    pub path: String,
    pub media_type: String,
    pub sha256: String,
    pub bytes: u64,
    pub width: u32,
    pub height: u32,
    #[serde(default)]
    pub frame_rate: Option<f64>,
    #[serde(default)]
    pub duration_ms: Option<u64>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
#[allow(clippy::struct_excessive_bools)]
pub struct MotionBehavior {
    pub purpose: MotionPurpose,
    #[serde(default)]
    pub animated_properties: BTreeSet<String>,
    pub easing: String,
    pub blocks_interaction: bool,
    pub autoplay: bool,
    pub looped: bool,
    pub muted: bool,
    pub reduced_motion: ReducedMotionBehavior,
    #[serde(default)]
    pub fallback_path: Option<String>,
    #[serde(default)]
    pub fallback_sha256: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct MotionCaptureContext {
    pub viewport_width: u32,
    pub viewport_height: u32,
    pub locale: String,
    pub timezone: String,
    pub network_mode: MotionNetworkMode,
    pub privacy_safe: bool,
    pub synthetic_data: bool,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct VisualMotionAsset {
    pub id: String,
    pub kind: VisualMotionKind,
    pub source: VisualMotionSource,
    pub generator: VisualMotionGenerator,
    pub output: VisualMotionOutput,
    pub behavior: MotionBehavior,
    pub capture: MotionCaptureContext,
    pub baseline_target_id: String,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct VisualMotionManifest {
    pub schema: String,
    pub project_id: String,
    pub source_digest: String,
    pub assets: Vec<VisualMotionAsset>,
}

impl VisualMotionManifest {
    fn validate_for(&self, input: &QualityInput<'_>) -> CompilerResult<()> {
        if self.schema != VISUAL_MOTION_MANIFEST_SCHEMA {
            return Err(motion_error(
                "visual-motion-manifest",
                format!(
                    "unsupported visual-motion manifest schema {:?}",
                    self.schema
                ),
                "Use identity.visual-motion-manifest/v1.",
            ));
        }
        if self.project_id != input.model.project_id {
            return Err(motion_error(
                "projectId",
                "visual-motion manifest project differs from the resolved Brand Kit".to_owned(),
                "Generate motion evidence from the same resolved project.",
            ));
        }
        if self.source_digest != input.model.source_digest {
            return Err(motion_error(
                "sourceDigest",
                "visual-motion manifest source digest differs from the resolved Brand Kit"
                    .to_owned(),
                "Recapture or regenerate the assets from the current canonical source.",
            ));
        }
        let mut ids = BTreeSet::new();
        for asset in &self.assets {
            if !ids.insert(asset.id.as_str()) {
                return Err(motion_error(
                    &asset.id,
                    "visual-motion asset id is declared more than once".to_owned(),
                    "Keep one provenance record per stable asset id.",
                ));
            }
        }
        Ok(())
    }
}

pub struct MotionQualityExtension<'a> {
    policy: &'a MotionPolicy,
    manifest: &'a VisualMotionManifest,
}

impl<'a> MotionQualityExtension<'a> {
    #[must_use]
    pub fn new(policy: &'a MotionPolicy, manifest: &'a VisualMotionManifest) -> Self {
        Self { policy, manifest }
    }

    pub fn evaluate(
        &self,
        harness: &QualityHarness,
        input: &QualityInput<'_>,
    ) -> CompilerResult<QualityReport> {
        let mut report = harness.evaluate(input)?;
        report.checks.extend(self.checks(input)?);
        normalize_report(&mut report);
        Ok(report)
    }

    pub fn checks(&self, input: &QualityInput<'_>) -> CompilerResult<Vec<QualityCheck>> {
        self.policy.validate()?;
        self.manifest.validate_for(input)?;
        let baselines = input.baselines.by_target()?;
        let mut checks = Vec::new();

        for asset in &self.manifest.assets {
            let source_context = Some(asset.source.reference.clone());
            let generated_context = Some(asset.output.path.clone());
            checks.extend(source_checks(input, asset));
            checks.extend(capture_checks(self.policy, asset));
            checks.extend(behavior_checks(self.policy, input.human_reviews, asset));

            let bytes = input.artifacts.read(&asset.output.path)?;
            match bytes {
                Some(bytes) => {
                    checks.extend(output_checks(self.policy, asset, &bytes));
                    checks.push(baseline_check(
                        input.human_reviews,
                        asset,
                        baselines.get(asset.baseline_target_id.as_str()).copied(),
                        &bytes,
                    ));
                }
                None => checks.push(make_check(
                    format!("motion.output-present.{}", asset.id),
                    QualityCategory::Reproducibility,
                    QualityStatus::Failed,
                    true,
                    true,
                    Some(asset.id.clone()),
                    source_context,
                    generated_context,
                    "Generated visual-motion asset is missing.",
                    "Regenerate or recapture the asset from the recorded source and fixture.",
                )),
            }

            if requires_fallback(asset) {
                checks.push(fallback_check(input, asset)?);
            }
        }

        Ok(checks)
    }
}

fn normalize_report(report: &mut QualityReport) {
    report.checks.sort_by(|left, right| {
        left.category
            .cmp(&right.category)
            .then_with(|| left.id.cmp(&right.id))
            .then_with(|| left.subject.cmp(&right.subject))
    });
    report.coverage = coverage(&report.checks);
    report.release_allowed = report.checks.iter().all(|check| {
        !check.blocking
            || !matches!(
                check.status,
                QualityStatus::Failed | QualityStatus::ReviewRequired
            )
    });
}

fn coverage(checks: &[QualityCheck]) -> QualityCoverage {
    let mut coverage = QualityCoverage {
        total: checks.len(),
        automated: checks.iter().filter(|check| check.automated).count(),
        ..QualityCoverage::default()
    };
    for check in checks {
        match check.status {
            QualityStatus::Passed => coverage.passed += 1,
            QualityStatus::Warning => coverage.warnings += 1,
            QualityStatus::Failed => coverage.failed += 1,
            QualityStatus::Skipped => coverage.skipped += 1,
            QualityStatus::ReviewRequired => coverage.review_required += 1,
        }
    }
    coverage
}

fn source_checks(input: &QualityInput<'_>, asset: &VisualMotionAsset) -> Vec<QualityCheck> {
    let mut checks = Vec::new();
    let source = &asset.source;
    let valid_base = !source.creator.trim().is_empty()
        && !source.reference.trim().is_empty()
        && valid_sha256(&source.sha256)
        && !source.license_spdx.trim().is_empty();
    checks.push(make_check(
        format!("motion.provenance.source.{}", asset.id),
        QualityCategory::Provenance,
        status(valid_base),
        true,
        true,
        Some(asset.id.clone()),
        Some(source.reference.clone()),
        Some(asset.output.path.clone()),
        if valid_base {
            "Visual-motion source records creator, reference, digest, and license."
        } else {
            "Visual-motion source provenance is incomplete or malformed."
        },
        "Record creator, source reference, SHA-256 digest, and SPDX license before release.",
    ));

    let approved = input.model.approvals.contains(&source.approval);
    checks.push(make_check(
        format!("motion.provenance.approval.{}", asset.id),
        QualityCategory::Provenance,
        status(approved),
        true,
        true,
        Some(asset.id.clone()),
        Some(source.reference.clone()),
        Some(asset.output.path.clone()),
        if approved {
            "Visual-motion source resolves to an approved human decision."
        } else {
            "Visual-motion source approval is absent from the resolved decision set."
        },
        "Approve the canonical source or candidate before deriving visual-motion assets.",
    ));

    let capture_lineage = if source.method == VisualMotionSourceMethod::Captured {
        source
            .repository
            .as_ref()
            .is_some_and(|value| !value.trim().is_empty())
            && source
                .commit
                .as_ref()
                .is_some_and(|value| valid_commit(value))
            && source
                .script_path
                .as_ref()
                .is_some_and(|value| !value.trim().is_empty())
            && source
                .fixture_path
                .as_ref()
                .is_some_and(|value| !value.trim().is_empty())
            && source
                .fixture_sha256
                .as_ref()
                .is_some_and(|value| valid_sha256(value))
    } else {
        true
    };
    checks.push(make_check(
        format!("motion.provenance.capture-lineage.{}", asset.id),
        QualityCategory::Provenance,
        status(capture_lineage),
        true,
        true,
        Some(asset.id.clone()),
        Some(source.reference.clone()),
        Some(asset.output.path.clone()),
        if capture_lineage {
            "Capture lineage is complete for the declared source method."
        } else {
            "Captured asset is missing immutable repository/script/fixture lineage."
        },
        "Record repository, 40-character commit, source script, fixture path, and fixture SHA-256.",
    ));
    checks
}

fn capture_checks(policy: &MotionPolicy, asset: &VisualMotionAsset) -> Vec<QualityCheck> {
    let capture = &asset.capture;
    let deterministic = policy.allowed_network_modes.contains(&capture.network_mode);
    let privacy = capture.privacy_safe && capture.synthetic_data;
    let viewport = capture.viewport_width > 0
        && capture.viewport_height > 0
        && capture.viewport_width <= policy.maximum_dimension_pixels
        && capture.viewport_height <= policy.maximum_dimension_pixels;

    vec![
        make_check(
            format!("motion.capture.network.{}", asset.id),
            QualityCategory::Reproducibility,
            status(deterministic),
            true,
            true,
            Some(asset.id.clone()),
            Some(asset.source.reference.clone()),
            Some(asset.output.path.clone()),
            if deterministic {
                "Capture uses an offline or recorded-fixture network mode."
            } else {
                "Capture depends on live network state."
            },
            "Capture against offline or recorded fixtures so the asset is reproducible.",
        ),
        make_check(
            format!("motion.capture.privacy.{}", asset.id),
            QualityCategory::Provenance,
            status(privacy),
            true,
            true,
            Some(asset.id.clone()),
            Some(asset.source.reference.clone()),
            Some(asset.output.path.clone()),
            if privacy {
                "Capture is declared privacy-safe and uses synthetic data."
            } else {
                "Capture is not both privacy-safe and synthetic."
            },
            "Replace captured personal/secret data with deterministic synthetic fixtures.",
        ),
        make_check(
            format!("motion.capture.viewport.{}", asset.id),
            QualityCategory::Performance,
            status(viewport),
            true,
            true,
            Some(asset.id.clone()),
            Some(format!(
                "{}x{} {} {}",
                capture.viewport_width, capture.viewport_height, capture.locale, capture.timezone
            )),
            Some(asset.output.path.clone()),
            if viewport {
                "Capture viewport is within the configured deterministic dimension budget."
            } else {
                "Capture viewport is missing or exceeds the configured dimension budget."
            },
            "Use a versioned viewport no larger than the motion policy maximum dimension.",
        ),
    ]
}

#[allow(clippy::too_many_lines)]
fn behavior_checks(
    policy: &MotionPolicy,
    reviews: &[HumanReviewEvidence],
    asset: &VisualMotionAsset,
) -> Vec<QualityCheck> {
    let behavior = &asset.behavior;
    let properties_valid = if behavior.purpose == MotionPurpose::StaticImagery
        || behavior.purpose == MotionPurpose::DemoCapture
    {
        behavior.animated_properties.is_empty()
            || behavior
                .animated_properties
                .iter()
                .all(|property| policy.allowed_animated_properties.contains(property))
    } else {
        !behavior.animated_properties.is_empty()
            && behavior
                .animated_properties
                .iter()
                .all(|property| policy.allowed_animated_properties.contains(property))
    };
    let easing_valid = behavior.purpose == MotionPurpose::StaticImagery
        || behavior.purpose == MotionPurpose::DemoCapture
        || policy.allowed_easing.contains(&behavior.easing);
    let autoplay_valid = !behavior.autoplay
        || (behavior.purpose == MotionPurpose::LandingSequence
            && behavior.muted
            && !behavior.looped);
    let loop_valid = !behavior.looped || behavior.purpose == MotionPurpose::ContinuousStatus;

    let mut checks = vec![
        make_check(
            format!("motion.properties.{}", asset.id),
            QualityCategory::Performance,
            status(properties_valid),
            true,
            true,
            Some(asset.id.clone()),
            Some(asset.source.reference.clone()),
            Some(asset.output.path.clone()),
            if properties_valid {
                "Declared UI movement uses only policy-approved cheap properties."
            } else {
                "Declared UI movement uses missing or disallowed animated properties."
            },
            "Prefer transform/opacity and avoid layout-property animation.",
        ),
        make_check(
            format!("motion.easing.{}", asset.id),
            QualityCategory::VisualIntegrity,
            status(easing_valid),
            true,
            true,
            Some(asset.id.clone()),
            Some(asset.source.reference.clone()),
            Some(asset.output.path.clone()),
            if easing_valid {
                "Motion easing is compatible with the meaning-first decelerating policy."
            } else {
                "Motion easing is outside the approved standard/ease-out family."
            },
            "Use a standard decelerating easing; bounce/elastic motion requires a versioned exception.",
        ),
        make_check(
            format!("motion.interaction.{}", asset.id),
            QualityCategory::Accessibility,
            status(!behavior.blocks_interaction),
            true,
            true,
            Some(asset.id.clone()),
            Some(asset.source.reference.clone()),
            Some(asset.output.path.clone()),
            if behavior.blocks_interaction {
                "Motion blocks the user's next interaction."
            } else {
                "Motion does not gate subsequent interaction."
            },
            "Make content interactive immediately; animation must never become a wait state.",
        ),
        make_check(
            format!("motion.autoplay.{}", asset.id),
            QualityCategory::Accessibility,
            status(autoplay_valid),
            true,
            true,
            Some(asset.id.clone()),
            Some(asset.source.reference.clone()),
            Some(asset.output.path.clone()),
            if autoplay_valid {
                "Autoplay behavior is absent or bounded to a muted non-looping landing sequence."
            } else {
                "Autoplay is not a muted non-looping landing sequence."
            },
            "Disable autoplay, or constrain it to a muted bounded landing sequence with a reduced-motion fallback.",
        ),
        make_check(
            format!("motion.loop.{}", asset.id),
            QualityCategory::Accessibility,
            status(loop_valid),
            true,
            true,
            Some(asset.id.clone()),
            Some(asset.source.reference.clone()),
            Some(asset.output.path.clone()),
            if loop_valid {
                "Looping is absent or limited to semantic continuous-status motion."
            } else {
                "Non-status motion is configured to loop indefinitely."
            },
            "Remove the loop or reclassify a genuine status indicator with a reduced-motion fallback.",
        ),
    ];

    if behavior.purpose != MotionPurpose::StaticImagery {
        checks.push(human_review_check(
            reviews,
            format!("motion.meaning.{}", asset.id),
            QualityCategory::VisualIntegrity,
            &asset.id,
            &asset.source.reference,
            &asset.output.path,
            "A human must confirm that the motion communicates a meaningful state or narrative change.",
            "Review the sequence in context and record the semantic-purpose decision.",
        ));
    }
    if matches!(
        behavior.purpose,
        MotionPurpose::Transition
            | MotionPurpose::LandingSequence
            | MotionPurpose::MicroInteraction
    ) {
        checks.push(human_review_check(
            reviews,
            format!("motion.direction.{}", asset.id),
            QualityCategory::VisualIntegrity,
            &asset.id,
            &asset.source.reference,
            &asset.output.path,
            "A human must confirm that movement direction/origin matches the interaction or narrative context.",
            "Review entrance/exit symmetry and trigger origin, then record the direction decision.",
        ));
    }
    checks
}

#[allow(clippy::too_many_lines)]
fn output_checks(
    policy: &MotionPolicy,
    asset: &VisualMotionAsset,
    bytes: &[u8],
) -> Vec<QualityCheck> {
    let output = &asset.output;
    let actual_bytes = u64::try_from(bytes.len()).unwrap_or(u64::MAX);
    let digest_valid = sha256_hex(bytes) == output.sha256 && actual_bytes == output.bytes;
    let byte_budget = actual_bytes <= policy.byte_budget(asset.behavior.purpose);
    let dimensions = output.width > 0
        && output.height > 0
        && output.width <= policy.maximum_dimension_pixels
        && output.height <= policy.maximum_dimension_pixels;
    let frame_rate = output
        .frame_rate
        .is_none_or(|value| value.is_finite() && value > 0.0 && value <= policy.maximum_frame_rate);
    let duration = match policy.duration_budget(asset.behavior.purpose) {
        Some(maximum) => output.duration_ms.is_some_and(|value| value <= maximum),
        None => output.duration_ms.is_none_or(|value| value == 0),
    };

    vec![
        make_check(
            format!("motion.output-digest.{}", asset.id),
            QualityCategory::Reproducibility,
            status(digest_valid),
            true,
            true,
            Some(asset.id.clone()),
            Some(asset.source.reference.clone()),
            Some(output.path.clone()),
            if digest_valid {
                "Generated asset bytes match the visual-motion manifest digest and byte count."
            } else {
                "Generated asset bytes drift from the visual-motion manifest."
            },
            "Discard the drifted asset and regenerate from the recorded source/fixture.",
        ),
        make_check(
            format!("motion.file-size.{}", asset.id),
            QualityCategory::Performance,
            status(byte_budget),
            true,
            true,
            Some(asset.id.clone()),
            Some(asset.source.reference.clone()),
            Some(output.path.clone()),
            format!(
                "Generated asset is {actual_bytes} bytes; purpose budget is {} bytes.",
                policy.byte_budget(asset.behavior.purpose)
            ),
            "Optimize the asset or explicitly version a different purpose/profile budget.",
        ),
        make_check(
            format!("motion.dimensions.{}", asset.id),
            QualityCategory::Performance,
            status(dimensions),
            true,
            true,
            Some(asset.id.clone()),
            Some(asset.source.reference.clone()),
            Some(output.path.clone()),
            format!(
                "Generated asset dimensions are {}x{}.",
                output.width, output.height
            ),
            "Resize the capture/asset within the configured maximum output dimension.",
        ),
        make_check(
            format!("motion.frame-rate.{}", asset.id),
            QualityCategory::Performance,
            status(frame_rate),
            true,
            true,
            Some(asset.id.clone()),
            Some(asset.source.reference.clone()),
            Some(output.path.clone()),
            match output.frame_rate {
                Some(value) => format!("Generated asset frame rate is {value:.2} fps."),
                None => "Generated asset has no frame-rate field for this format.".to_owned(),
            },
            "Keep captured motion at or below the configured frame-rate budget.",
        ),
        make_check(
            format!("motion.duration.{}", asset.id),
            QualityCategory::Accessibility,
            status(duration),
            true,
            true,
            Some(asset.id.clone()),
            Some(asset.source.reference.clone()),
            Some(output.path.clone()),
            match (
                output.duration_ms,
                policy.duration_budget(asset.behavior.purpose),
            ) {
                (Some(value), Some(maximum)) => format!(
                    "Generated motion duration is {value} ms; purpose budget is {maximum} ms."
                ),
                (None, Some(maximum)) => {
                    format!("Generated motion has no duration; purpose budget is {maximum} ms.")
                }
                _ => "Static imagery has no motion duration budget.".to_owned(),
            },
            "Shorten the motion or intentionally version a different purpose-specific budget.",
        ),
    ]
}

fn baseline_check(
    reviews: &[HumanReviewEvidence],
    asset: &VisualMotionAsset,
    baseline: Option<&crate::quality::VisualBaseline>,
    bytes: &[u8],
) -> QualityCheck {
    let check_id = format!("visual.regression.{}", asset.baseline_target_id);
    let Some(baseline) = baseline else {
        return human_review_check(
            reviews,
            check_id,
            QualityCategory::VisualIntegrity,
            &asset.id,
            &asset.source.reference,
            &asset.output.path,
            "No approved visual baseline exists for this generated surface.",
            "Review the generated surface and record an approved baseline before release.",
        );
    };
    if baseline.sha256 == sha256_hex(bytes) {
        return make_check(
            check_id,
            QualityCategory::VisualIntegrity,
            QualityStatus::Passed,
            true,
            true,
            Some(asset.id.clone()),
            Some(baseline.source_context.clone()),
            Some(baseline.generated_context.clone()),
            "Generated visual-motion bytes match the approved baseline.",
            "No recovery required.",
        );
    }
    human_review_check(
        reviews,
        check_id,
        QualityCategory::VisualIntegrity,
        &asset.id,
        &baseline.source_context,
        &baseline.generated_context,
        "Generated visual-motion bytes differ from the approved baseline.",
        "Compare source/generated context and record an explicit human decision before release.",
    )
}

fn requires_fallback(asset: &VisualMotionAsset) -> bool {
    if asset.behavior.purpose == MotionPurpose::StaticImagery {
        return false;
    }
    match asset.behavior.reduced_motion {
        ReducedMotionBehavior::Instant => matches!(
            asset.behavior.purpose,
            MotionPurpose::LandingSequence
                | MotionPurpose::ContinuousStatus
                | MotionPurpose::DemoCapture
        ),
        ReducedMotionBehavior::StaticFallback | ReducedMotionBehavior::PairedReducedCapture => true,
    }
}

fn fallback_check(
    input: &QualityInput<'_>,
    asset: &VisualMotionAsset,
) -> CompilerResult<QualityCheck> {
    let Some(path) = asset.behavior.fallback_path.as_deref() else {
        return Ok(make_check(
            format!("motion.reduced-motion.{}", asset.id),
            QualityCategory::Accessibility,
            QualityStatus::Failed,
            true,
            true,
            Some(asset.id.clone()),
            Some(asset.source.reference.clone()),
            Some(asset.output.path.clone()),
            "Motion requires a reduced-motion fallback but no fallback path is declared.",
            "Provide a static or paired reduced-motion asset with an immutable digest.",
        ));
    };
    let Some(expected) = asset.behavior.fallback_sha256.as_deref() else {
        return Ok(make_check(
            format!("motion.reduced-motion.{}", asset.id),
            QualityCategory::Accessibility,
            QualityStatus::Failed,
            true,
            true,
            Some(asset.id.clone()),
            Some(asset.source.reference.clone()),
            Some(path.to_owned()),
            "Reduced-motion fallback has no SHA-256 digest.",
            "Record the exact fallback digest before release.",
        ));
    };
    let bytes = input.artifacts.read(path)?;
    let valid = bytes
        .as_ref()
        .is_some_and(|bytes| valid_sha256(expected) && sha256_hex(bytes) == expected);
    Ok(make_check(
        format!("motion.reduced-motion.{}", asset.id),
        QualityCategory::Accessibility,
        status(valid),
        true,
        true,
        Some(asset.id.clone()),
        Some(asset.source.reference.clone()),
        Some(path.to_owned()),
        if valid {
            "Reduced-motion fallback exists and matches its immutable digest."
        } else {
            "Reduced-motion fallback is missing or does not match its digest."
        },
        "Generate the declared static/paired reduced-motion projection and update provenance through human review.",
    ))
}

#[allow(clippy::too_many_arguments)]
fn human_review_check(
    reviews: &[HumanReviewEvidence],
    check_id: String,
    category: QualityCategory,
    subject: &str,
    source_context: &str,
    generated_context: &str,
    message: &str,
    recovery: &str,
) -> QualityCheck {
    let review = reviews.iter().find(|review| review.check_id == check_id);
    let status = match review {
        Some(review) if review.approved => QualityStatus::Passed,
        Some(_) => QualityStatus::Failed,
        None => QualityStatus::ReviewRequired,
    };
    make_check(
        check_id,
        category,
        status,
        true,
        false,
        Some(subject.to_owned()),
        Some(source_context.to_owned()),
        Some(generated_context.to_owned()),
        if status == QualityStatus::Passed {
            "Required human visual-motion review is approved."
        } else {
            message
        },
        if status == QualityStatus::Passed {
            "No recovery required."
        } else {
            recovery
        },
    )
}

#[allow(clippy::too_many_arguments)]
fn make_check(
    id: String,
    category: QualityCategory,
    status: QualityStatus,
    blocking: bool,
    automated: bool,
    subject: Option<String>,
    source_context: Option<String>,
    generated_context: Option<String>,
    message: impl Into<String>,
    recovery: impl Into<String>,
) -> QualityCheck {
    QualityCheck {
        id,
        category,
        status,
        blocking,
        automated,
        subject,
        source_context,
        generated_context,
        message: message.into(),
        recovery: recovery.into(),
    }
}

fn status(valid: bool) -> QualityStatus {
    if valid {
        QualityStatus::Passed
    } else {
        QualityStatus::Failed
    }
}

fn valid_sha256(value: &str) -> bool {
    value.len() == 64
        && value
            .chars()
            .all(|character| character.is_ascii_hexdigit() && !character.is_ascii_uppercase())
}

fn valid_commit(value: &str) -> bool {
    value.len() == 40
        && value
            .chars()
            .all(|character| character.is_ascii_hexdigit() && !character.is_ascii_uppercase())
}

fn motion_error(path: &str, message: String, recovery: &str) -> CompilerError {
    CompilerError::new(
        FailureKind::Invalid,
        Diagnostic::error(
            "IDN3301",
            FailureKind::Invalid,
            Some(path.to_owned()),
            message,
            recovery.to_owned(),
        ),
    )
}
