// Copyright 2026 Ego Hygiene
// SPDX-License-Identifier: MIT

use std::collections::BTreeMap;

use resvg::{tiny_skia, usvg};
use serde::Serialize;
use serde_json::{Map, Value, json};

use crate::compiler::{
    CompilerError, CompilerResult, Diagnostic, FailureKind, ProjectionTarget, sha256_hex,
};

use super::archive::deterministic_zip;
use super::model::{BrandKitModel, BrandKitToken};

const PACKAGE_VERSION: &str = "1.0.0";
const MASKABLE_CONTENT_FRACTION: f32 = 0.54;

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct ChecksumEntry {
    sha256: String,
    bytes: u64,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
struct PackageIndex {
    schema: &'static str,
    version: &'static str,
    project_id: String,
    source_digest: String,
    profiles: Vec<&'static str>,
    files: BTreeMap<String, ChecksumEntry>,
}

pub(super) fn render_tokens(
    model: &BrandKitModel,
    target: &ProjectionTarget,
) -> CompilerResult<Vec<u8>> {
    match string_parameter(target, "format")? {
        "dtcg-json" => render_dtcg_json(model),
        "css" => Ok(render_css(model, false).into_bytes()),
        "document-css" => Ok(render_css(model, true).into_bytes()),
        "javascript" => render_javascript(model),
        "typescript" => Ok(render_typescript(model).into_bytes()),
        "tailwind" => render_tailwind(model),
        "package-json" => package_json(
            "@egohygiene/identity-tokens",
            "Portable semantic design-token projections generated by Identity.",
            [
                ("./tokens.json", "./tokens.json"),
                ("./tokens.css", "./tokens.css"),
                ("./tokens.js", "./tokens.js"),
                ("./tailwind", "./tailwind.theme.json"),
            ],
            Some("./tokens.d.ts"),
        ),
        format => Err(render_error(
            &target.relative_path,
            format!("unsupported token projection format {format:?}"),
        )),
    }
}

pub(super) fn render_metadata(
    model: &BrandKitModel,
    target: &ProjectionTarget,
) -> CompilerResult<Vec<u8>> {
    match string_parameter(target, "format")? {
        "metadata-json" => pretty_json(&json!({
            "schema": "identity.public-metadata/v1",
            "projectId": model.project_id,
            "displayName": model.project.display_name,
            "repository": model.project.repository,
            "tagline": model.project.tagline,
            "social": {
                "defaultCard": "social/card-1200x630.png",
                "githubPreview": "github/social-preview.png"
            }
        })),
        "open-graph" => Ok(render_open_graph(model).into_bytes()),
        "web-manifest-icons" => pretty_json(&json!({
            "schema": "identity.web-manifest-icons/v1",
            "icons": [
                {"src": "pwa/icon-192.png", "sizes": "192x192", "type": "image/png", "purpose": "any"},
                {"src": "pwa/icon-512.png", "sizes": "512x512", "type": "image/png", "purpose": "any"},
                {"src": "pwa/icon-maskable-512.png", "sizes": "512x512", "type": "image/png", "purpose": "maskable"}
            ]
        })),
        "package-json" => package_json(
            "@egohygiene/identity-metadata",
            "Public metadata and Open Graph projections generated by Identity.",
            [
                ("./metadata.json", "./metadata.json"),
                ("./open-graph.html", "./open-graph.html"),
            ],
            None,
        ),
        format => Err(render_error(
            &target.relative_path,
            format!("unsupported metadata projection format {format:?}"),
        )),
    }
}

pub(super) fn render_guidance(
    model: &BrandKitModel,
    target: &ProjectionTarget,
) -> CompilerResult<Vec<u8>> {
    match string_parameter(target, "format")? {
        "json" => pretty_json(&json!({
            "schema": "identity.guidance-package/v1",
            "projectId": model.project_id,
            "voice": model.guidance.voice,
            "usage": model.guidance.usage,
            "status": {
                "voice": if model.guidance.voice.is_some() { "declared" } else { "not-declared" },
                "usage": if model.guidance.usage.is_some() { "declared" } else { "not-declared" }
            }
        })),
        "markdown" => Ok(render_guidance_markdown(model).into_bytes()),
        format => Err(render_error(
            &target.relative_path,
            format!("unsupported guidance projection format {format:?}"),
        )),
    }
}

pub(super) fn render_source_svg(
    model: &BrandKitModel,
    target: &ProjectionTarget,
) -> CompilerResult<Vec<u8>> {
    let role = string_parameter(target, "role")?;
    let source = model.source(role)?;
    if source.media_type != "image/svg+xml" {
        return Err(render_error(
            &target.relative_path,
            format!("source role {role:?} is not an SVG asset"),
        ));
    }
    let bytes = source.text.as_bytes();
    if sha256_hex(bytes) != source.sha256 {
        return Err(render_error(
            &target.relative_path,
            format!("source role {role:?} does not match its approved SHA-256 digest"),
        ));
    }
    Ok(bytes.to_vec())
}

// Built-in raster profiles bound dimensions to small platform sizes; tiny-skia uses f32 transforms.
#[allow(clippy::cast_precision_loss)]
pub(super) fn render_raster(
    model: &BrandKitModel,
    target: &ProjectionTarget,
) -> CompilerResult<Vec<u8>> {
    let width = u32_parameter(target, "width")?;
    let height = u32_parameter(target, "height")?;
    let mode = string_parameter(target, "mode")?;
    let maskable = bool_parameter(target, "maskable")?;
    let role = string_parameter(target, "sourceRole")?;
    let source = model.source(role)?;
    if source.media_type != "image/svg+xml" {
        return Err(render_error(
            &target.relative_path,
            format!("raster source role {role:?} must be image/svg+xml"),
        ));
    }
    if sha256_hex(source.text.as_bytes()) != source.sha256 {
        return Err(render_error(
            &target.relative_path,
            format!("raster source role {role:?} failed its approved source digest"),
        ));
    }

    let options = usvg::Options::default();
    let tree = usvg::Tree::from_data(source.text.as_bytes(), &options).map_err(|error| {
        render_error(
            &target.relative_path,
            format!("cannot parse approved SVG source for raster projection: {error}"),
        )
    })?;
    let mut pixmap = tiny_skia::Pixmap::new(width, height).ok_or_else(|| {
        render_error(
            &target.relative_path,
            "cannot allocate target raster dimensions".to_owned(),
        )
    })?;

    if maskable || mode == "social-card" {
        pixmap.fill(token_color(model, "color.canvas")?);
    }

    let fraction = if maskable {
        MASKABLE_CONTENT_FRACTION
    } else if mode == "social-card" {
        0.42
    } else {
        0.88
    };
    let source_size = tree.size();
    let available_width = width as f32 * fraction;
    let available_height = height as f32 * fraction;
    let scale =
        (available_width / source_size.width()).min(available_height / source_size.height());
    let rendered_width = source_size.width() * scale;
    let rendered_height = source_size.height() * scale;
    let translate_x = (width as f32 - rendered_width) / 2.0;
    let translate_y = (height as f32 - rendered_height) / 2.0;
    let transform =
        tiny_skia::Transform::from_row(scale, 0.0, 0.0, scale, translate_x, translate_y);
    resvg::render(&tree, transform, &mut pixmap.as_mut());
    pixmap.encode_png().map_err(|error| {
        render_error(
            &target.relative_path,
            format!("cannot encode deterministic PNG projection: {error}"),
        )
    })
}

pub(super) fn render_package(
    model: &BrandKitModel,
    target: &ProjectionTarget,
) -> CompilerResult<Vec<u8>> {
    let entries = archive_entries(model)?;
    match string_parameter(target, "format")? {
        "index-json" => render_package_index(model, &entries),
        "checksums-json" => render_checksums(&entries),
        "zip" => deterministic_zip(&entries),
        format => Err(render_error(
            &target.relative_path,
            format!("unsupported Brand Kit package format {format:?}"),
        )),
    }
}

pub(super) fn expected_raster_dimensions(target: &ProjectionTarget) -> CompilerResult<(u32, u32)> {
    Ok((
        u32_parameter(target, "width")?,
        u32_parameter(target, "height")?,
    ))
}

pub(super) fn is_maskable(target: &ProjectionTarget) -> CompilerResult<bool> {
    bool_parameter(target, "maskable")
}

pub(super) fn standard_maskable_fraction() -> f32 {
    MASKABLE_CONTENT_FRACTION
}

fn render_dtcg_json(model: &BrandKitModel) -> CompilerResult<Vec<u8>> {
    let mut root = Map::new();
    root.insert(
        "$description".to_owned(),
        Value::String(format!(
            "Generated semantic token projection for {}.",
            model.project.display_name
        )),
    );
    root.insert(
        "$extensions".to_owned(),
        json!({
            "org.egohygiene.identity.projection": {
                "schema": "identity.tokens-package/v1",
                "projectId": model.project_id,
                "sourceDigest": model.source_digest,
                "version": PACKAGE_VERSION
            }
        }),
    );
    for (path, token) in &model.tokens {
        insert_dtcg_token(&mut root, path, token)?;
    }
    pretty_json(&Value::Object(root))
}

fn insert_dtcg_token(
    root: &mut Map<String, Value>,
    path: &str,
    token: &BrandKitToken,
) -> CompilerResult<()> {
    let segments = path.split('.').collect::<Vec<_>>();
    if segments.is_empty() {
        return Err(render_error(path, "token path is empty".to_owned()));
    }
    insert_dtcg_segments(root, &segments, token, path)
}

fn insert_dtcg_segments(
    current: &mut Map<String, Value>,
    segments: &[&str],
    token: &BrandKitToken,
    full_path: &str,
) -> CompilerResult<()> {
    let Some((head, tail)) = segments.split_first() else {
        return Err(render_error(full_path, "token path is empty".to_owned()));
    };
    if tail.is_empty() {
        current.insert(
            (*head).to_owned(),
            json!({
                "$type": token.token_type,
                "$value": token.value,
                "$extensions": {
                    "org.egohygiene.identity.projection": {
                        "sourceLayer": token.source_layer,
                        "overrideReason": token.override_reason,
                        "approval": token.approval
                    }
                }
            }),
        );
        return Ok(());
    }

    if !current.contains_key(*head) {
        current.insert((*head).to_owned(), Value::Object(Map::new()));
    }
    let group = current
        .get_mut(*head)
        .and_then(Value::as_object_mut)
        .ok_or_else(|| {
            render_error(
                full_path,
                format!("token path {full_path:?} collides with a scalar token"),
            )
        })?;
    insert_dtcg_segments(group, tail, token, full_path)
}

fn render_css(model: &BrandKitModel, document: bool) -> String {
    let mut output = String::new();
    output.push_str("/* Generated by egohygiene/identity. Do not edit. */\n:root {\n");
    for (path, token) in &model.tokens {
        if let Some(value) = css_token_value(token) {
            output.push_str("  --identity-");
            output.push_str(&css_identifier(path));
            output.push_str(": ");
            output.push_str(&value);
            output.push_str(";\n");
        }
    }
    output.push_str("}\n");
    if document {
        output.push_str("\nhtml { color-scheme: light dark; }\n");
        output.push_str("body {\n");
        output.push_str("  color: var(--identity-color-text);\n");
        output.push_str("  background: var(--identity-color-canvas);\n");
        if model.tokens.contains_key("typography.body.family") {
            output.push_str("  font-family: var(--identity-typography-body-family);\n");
        }
        output.push_str("  font-size: 16px;\n  line-height: 1.5;\n}\n");
        output.push_str("@media print { body { background: white; color: black; } }\n");
    }
    output
}

fn render_javascript(model: &BrandKitModel) -> CompilerResult<Vec<u8>> {
    let values = model
        .tokens
        .iter()
        .map(|(path, token)| (path.clone(), token.value.clone()))
        .collect::<BTreeMap<_, _>>();
    let serialized = serde_json::to_string_pretty(&values).map_err(|error| {
        render_error(
            "tokens",
            format!("cannot serialize JavaScript token projection: {error}"),
        )
    })?;
    Ok(format!(
        "// Generated by egohygiene/identity. Do not edit.\nexport const tokens = Object.freeze({serialized});\nexport default tokens;\n"
    )
    .into_bytes())
}

fn render_typescript(model: &BrandKitModel) -> String {
    let union = model
        .tokens
        .keys()
        .map(|path| format!("\"{path}\""))
        .collect::<Vec<_>>()
        .join(" | ");
    format!(
        "// Generated by egohygiene/identity. Do not edit.\nexport type IdentityTokenPath = {union};\nexport declare const tokens: Readonly<Record<IdentityTokenPath, unknown>>;\nexport default tokens;\n"
    )
}

fn render_tailwind(model: &BrandKitModel) -> CompilerResult<Vec<u8>> {
    let mut colors = BTreeMap::new();
    let mut font_family = BTreeMap::new();
    for (path, token) in &model.tokens {
        if let Some(name) = path.strip_prefix("color.")
            && token.token_type == "color"
            && let Some(value) = css_token_value(token)
        {
            colors.insert(name.replace('.', "-"), value);
        }
        if let Some(name) = path.strip_prefix("typography.")
            && path.ends_with(".family")
            && token.token_type == "fontFamily"
        {
            font_family.insert(name.replace(".family", ""), token.value.clone());
        }
    }
    pretty_json(&json!({
        "schema": "identity.tailwind-theme/v1",
        "theme": {
            "extend": {
                "colors": colors,
                "fontFamily": font_family
            }
        }
    }))
}

fn render_open_graph(model: &BrandKitModel) -> String {
    format!(
        "<!-- Generated by egohygiene/identity. Do not edit. -->\n<meta property=\"og:title\" content=\"{}\" />\n<meta property=\"og:description\" content=\"{}\" />\n<meta property=\"og:type\" content=\"website\" />\n<meta property=\"og:image\" content=\"social/card-1200x630.png\" />\n<meta property=\"og:image:width\" content=\"1200\" />\n<meta property=\"og:image:height\" content=\"630\" />\n",
        escape_html_attribute(&model.project.display_name),
        escape_html_attribute(&model.project.tagline),
    )
}

fn render_guidance_markdown(model: &BrandKitModel) -> String {
    let mut output = format!(
        "# {} Brand Kit guidance\n\nGenerated by `egohygiene/identity`; canonical guidance remains under `.identity/`.\n\n",
        model.project.display_name
    );
    output.push_str("## Voice\n\n");
    match &model.guidance.voice {
        Some(value) => {
            output.push_str("```json\n");
            output.push_str(
                &serde_json::to_string_pretty(value).unwrap_or_else(|_| "null".to_owned()),
            );
            output.push_str("\n```\n\n");
        }
        None => output.push_str("Not declared in the current v1 source.\n\n"),
    }
    output.push_str("## Usage\n\n");
    match &model.guidance.usage {
        Some(value) => {
            output.push_str("```json\n");
            output.push_str(
                &serde_json::to_string_pretty(value).unwrap_or_else(|_| "null".to_owned()),
            );
            output.push_str("\n```\n");
        }
        None => output.push_str("Not declared in the current v1 source.\n"),
    }
    output
}

fn archive_entries(model: &BrandKitModel) -> CompilerResult<Vec<(String, Vec<u8>)>> {
    let source_target = synthetic_target("brand/mark.svg", [("role", json!("mark"))]);
    let mut entries = vec![
        (
            "brand/mark.svg".to_owned(),
            render_source_svg(model, &source_target)?,
        ),
        ("tokens/tokens.json".to_owned(), render_dtcg_json(model)?),
        (
            "tokens/tokens.css".to_owned(),
            render_css(model, false).into_bytes(),
        ),
        ("tokens/tokens.js".to_owned(), render_javascript(model)?),
        (
            "tokens/tokens.d.ts".to_owned(),
            render_typescript(model).into_bytes(),
        ),
        (
            "tokens/tailwind.theme.json".to_owned(),
            render_tailwind(model)?,
        ),
        (
            "docs/document.css".to_owned(),
            render_css(model, true).into_bytes(),
        ),
        (
            "metadata/metadata.json".to_owned(),
            pretty_json(&json!({
                "schema": "identity.public-metadata/v1",
                "projectId": model.project_id,
                "displayName": model.project.display_name,
                "repository": model.project.repository,
                "tagline": model.project.tagline
            }))?,
        ),
        (
            "metadata/open-graph.html".to_owned(),
            render_open_graph(model).into_bytes(),
        ),
        (
            "guidance/README.md".to_owned(),
            render_guidance_markdown(model).into_bytes(),
        ),
    ];
    entries.push((
        "pwa/icon-192.png".to_owned(),
        render_raster(
            model,
            &synthetic_raster_target("pwa/icon-192.png", 192, 192, "icon", false),
        )?,
    ));
    entries.push((
        "pwa/icon-512.png".to_owned(),
        render_raster(
            model,
            &synthetic_raster_target("pwa/icon-512.png", 512, 512, "icon", false),
        )?,
    ));
    entries.push((
        "pwa/icon-maskable-512.png".to_owned(),
        render_raster(
            model,
            &synthetic_raster_target("pwa/icon-maskable-512.png", 512, 512, "icon", true),
        )?,
    ));
    entries.push((
        "social/card-1200x630.png".to_owned(),
        render_raster(
            model,
            &synthetic_raster_target("social/card-1200x630.png", 1200, 630, "social-card", false),
        )?,
    ));
    entries.push((
        "github/social-preview.png".to_owned(),
        render_raster(
            model,
            &synthetic_raster_target("github/social-preview.png", 1280, 640, "social-card", false),
        )?,
    ));
    Ok(entries)
}

fn render_package_index(
    model: &BrandKitModel,
    entries: &[(String, Vec<u8>)],
) -> CompilerResult<Vec<u8>> {
    let files = checksum_map(entries)?;
    pretty_json(&PackageIndex {
        schema: "identity.brand-kit-package/v1",
        version: PACKAGE_VERSION,
        project_id: model.project_id.clone(),
        source_digest: model.source_digest.clone(),
        profiles: vec![
            "core", "web", "pwa", "github", "docs", "social", "tokens", "metadata",
        ],
        files,
    })
}

fn render_checksums(entries: &[(String, Vec<u8>)]) -> CompilerResult<Vec<u8>> {
    pretty_json(&json!({
        "schema": "identity.brand-kit-checksums/v1",
        "algorithm": "sha256",
        "files": checksum_map(entries)?
    }))
}

fn checksum_map(entries: &[(String, Vec<u8>)]) -> CompilerResult<BTreeMap<String, ChecksumEntry>> {
    let mut result = BTreeMap::new();
    for (path, bytes) in entries {
        result.insert(
            path.clone(),
            ChecksumEntry {
                sha256: sha256_hex(bytes),
                bytes: u64::try_from(bytes.len()).map_err(|error| {
                    render_error(
                        path,
                        format!("cannot represent package byte length: {error}"),
                    )
                })?,
            },
        );
    }
    Ok(result)
}

fn package_json<const N: usize>(
    name: &str,
    description: &str,
    exports: [(&str, &str); N],
    types: Option<&str>,
) -> CompilerResult<Vec<u8>> {
    let exports = exports
        .into_iter()
        .map(|(key, value)| (key.to_owned(), Value::String(value.to_owned())))
        .collect::<BTreeMap<_, _>>();
    pretty_json(&json!({
        "name": name,
        "version": PACKAGE_VERSION,
        "description": description,
        "private": false,
        "type": "module",
        "exports": exports,
        "types": types,
        "sideEffects": false
    }))
}

fn css_token_value(token: &BrandKitToken) -> Option<String> {
    match token.token_type.as_str() {
        "color" => color_css(&token.value),
        "duration" => duration_css(&token.value),
        "fontFamily" => font_family_css(&token.value),
        "number" | "fontWeight" => token.value.as_f64().map(|value| value.to_string()),
        "dimension" => dimension_css(&token.value),
        _ if token.value.is_string() => token.value.as_str().map(ToOwned::to_owned),
        _ => None,
    }
}

fn color_css(value: &Value) -> Option<String> {
    let object = value.as_object()?;
    if object.get("colorSpace")?.as_str()? != "srgb" {
        return None;
    }
    let components = object.get("components")?.as_array()?;
    if components.len() != 3 {
        return None;
    }
    let red = channel(components.first()?.as_f64()?);
    let green = channel(components.get(1)?.as_f64()?);
    let blue = channel(components.get(2)?.as_f64()?);
    let alpha = object.get("alpha").and_then(Value::as_f64).unwrap_or(1.0);
    if (alpha - 1.0).abs() < f64::EPSILON {
        Some(format!("#{red:02x}{green:02x}{blue:02x}"))
    } else {
        Some(format!("rgba({red}, {green}, {blue}, {alpha:.3})"))
    }
}

fn duration_css(value: &Value) -> Option<String> {
    let object = value.as_object()?;
    Some(format!(
        "{}{}",
        object.get("value")?.as_f64()?,
        object.get("unit")?.as_str()?
    ))
}

fn dimension_css(value: &Value) -> Option<String> {
    duration_css(value)
}

fn font_family_css(value: &Value) -> Option<String> {
    let values = value.as_array()?;
    let families = values
        .iter()
        .filter_map(Value::as_str)
        .map(|family| {
            if family.contains(' ') {
                format!("\"{}\"", family.replace('"', "\\\""))
            } else {
                family.to_owned()
            }
        })
        .collect::<Vec<_>>();
    (!families.is_empty()).then(|| families.join(", "))
}

fn token_color(model: &BrandKitModel, path: &str) -> CompilerResult<tiny_skia::Color> {
    let token = model.token(path)?;
    let object = token
        .value
        .as_object()
        .ok_or_else(|| render_error(path, "color token value must be an object".to_owned()))?;
    let components = object
        .get("components")
        .and_then(Value::as_array)
        .filter(|values| values.len() == 3)
        .ok_or_else(|| {
            render_error(
                path,
                "color token must contain three sRGB components".to_owned(),
            )
        })?;
    let red = channel_number(components.first(), path)?;
    let green = channel_number(components.get(1), path)?;
    let blue = channel_number(components.get(2), path)?;
    let alpha = channel(object.get("alpha").and_then(Value::as_f64).unwrap_or(1.0));
    Ok(tiny_skia::Color::from_rgba8(red, green, blue, alpha))
}

fn channel_number(value: Option<&Value>, path: &str) -> CompilerResult<u8> {
    value
        .and_then(Value::as_f64)
        .map(channel)
        .ok_or_else(|| render_error(path, "color component must be numeric".to_owned()))
}

// The value is clamped to [0, 1], scaled, and rounded before the intentional u8 conversion.
#[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
fn channel(value: f64) -> u8 {
    (value.clamp(0.0, 1.0) * 255.0).round() as u8
}

fn css_identifier(path: &str) -> String {
    path.chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || character == '-' {
                character.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect()
}

fn escape_html_attribute(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

fn pretty_json(value: &impl Serialize) -> CompilerResult<Vec<u8>> {
    let mut bytes = serde_json::to_vec_pretty(value).map_err(|error| {
        render_error(
            "serialization",
            format!("cannot serialize deterministic Brand Kit projection: {error}"),
        )
    })?;
    bytes.push(b'\n');
    Ok(bytes)
}

fn string_parameter<'a>(target: &'a ProjectionTarget, name: &str) -> CompilerResult<&'a str> {
    target
        .parameters
        .get(name)
        .and_then(Value::as_str)
        .ok_or_else(|| {
            render_error(
                &target.relative_path,
                format!("projection parameter {name:?} must be a string"),
            )
        })
}

fn u32_parameter(target: &ProjectionTarget, name: &str) -> CompilerResult<u32> {
    let value = target
        .parameters
        .get(name)
        .and_then(Value::as_u64)
        .ok_or_else(|| {
            render_error(
                &target.relative_path,
                format!("projection parameter {name:?} must be a positive integer"),
            )
        })?;
    u32::try_from(value).map_err(|error| {
        render_error(
            &target.relative_path,
            format!("projection parameter {name:?} is too large: {error}"),
        )
    })
}

fn bool_parameter(target: &ProjectionTarget, name: &str) -> CompilerResult<bool> {
    target
        .parameters
        .get(name)
        .and_then(Value::as_bool)
        .ok_or_else(|| {
            render_error(
                &target.relative_path,
                format!("projection parameter {name:?} must be a boolean"),
            )
        })
}

fn synthetic_target<const N: usize>(path: &str, entries: [(&str, Value); N]) -> ProjectionTarget {
    ProjectionTarget {
        id: "archive-source".to_owned(),
        profile: "archive".to_owned(),
        relative_path: path.to_owned(),
        adapter_id: "identity-source-svg".to_owned(),
        media_type: "image/svg+xml".to_owned(),
        parameters: entries
            .into_iter()
            .map(|(key, value)| (key.to_owned(), value))
            .collect(),
        required_approval: None,
        maximum_bytes: None,
    }
}

fn synthetic_raster_target(
    path: &str,
    width: u32,
    height: u32,
    mode: &str,
    maskable: bool,
) -> ProjectionTarget {
    synthetic_target(
        path,
        [
            ("width", json!(width)),
            ("height", json!(height)),
            ("mode", json!(mode)),
            ("maskable", json!(maskable)),
            ("sourceRole", json!("mark")),
        ],
    )
}

fn render_error(path: &str, message: String) -> CompilerError {
    CompilerError::new(
        FailureKind::Failed,
        Diagnostic::error(
            "IDN3301",
            FailureKind::Failed,
            Some(path.to_owned()),
            message,
            "Review the resolved Brand Kit model and versioned output profile, then regenerate from canonical source.",
        ),
    )
}
